[build]
  command = "npm install && npm run build"
  publish = "build/"  
  functions = "client/functions/"
  

[[redirects]]
  from = "/*"
  to = "/.client/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"



