[build]
  command = "npm --prefix client run build"
  publish = "build/"
  functions = "functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

