[build]
  command = "npm --prefix client run build"
  publish = "mukja/client/build/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[functions]
  external_node_modules = [
    path = "functions/location.js"
    path = "functions/popular-restaurants.js"
  ]