export const mockRestaurantData = [
  {
    id: "OyB0Kn1JBRBNgWVGS8CwTA",
    alias: "formoosa-san-diego",
    name: "formoosa",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/DDCHPwaX3VC_tg4ZClUCZg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/formoosa-san-diego?adjust_creative=wieZL2d874d6yAqQIh_gnQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=wieZL2d874d6yAqQIh_gnQ",
    review_count: 3720,
    categories: [
      {
        alias: "taiwanese",
        title: "Taiwanese",
      },
      {
        alias: "coffee",
        title: "Coffee & Tea",
      },
      {
        alias: "noodles",
        title: "Noodles",
      },
    ],
    rating: 4.7,
    coordinates: {
      latitude: 32.82461,
      longitude: -117.15571,
    },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "4646 Convoy St",
      address2: "",
      address3: "",
      city: "San Diego",
      zip_code: "92111",
      country: "US",
      state: "CA",
      display_address: ["4646 Convoy St", "San Diego, CA 92111"],
    },
    phone: "+18585679091",
    display_phone: "(858) 567-9091",
    distance: 3816.5306971354303,
  },
  {
    id: "UhF03LyD4DCoHPpEwQatwg",
    alias: "pelicana-chicken-san-diego-3",
    name: "Pelicana Chicken",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/O5T_7t616eoiF5awOp5xzw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/pelicana-chicken-san-diego-3?adjust_creative=wieZL2d874d6yAqQIh_gnQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=wieZL2d874d6yAqQIh_gnQ",
    review_count: 609,
    categories: [
      {
        alias: "chicken_wings",
        title: "Chicken Wings",
      },
      {
        alias: "korean",
        title: "Korean",
      },
      {
        alias: "beerbar",
        title: "Beer Bar",
      },
    ],
    rating: 4.3,
    coordinates: {
      latitude: 32.821263,
      longitude: -117.155911,
    },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "7767 Balboa Ave",
      address2: null,
      address3: "",
      city: "San Diego",
      zip_code: "92111",
      country: "US",
      state: "CA",
      display_address: ["7767 Balboa Ave", "San Diego, CA 92111"],
    },
    phone: "+18582782167",
    display_phone: "(858) 278-2167",
    distance: 3417.9099944823315,
  },
  {
    id: "Kcz7ZiGDnTLZRpMShlMyfQ",
    alias: "bafang-dumpling-san-diego",
    name: "Bafang Dumpling",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/f-K4tZR3GgC0C3lfyxQHkg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/bafang-dumpling-san-diego?adjust_creative=wieZL2d874d6yAqQIh_gnQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=wieZL2d874d6yAqQIh_gnQ",
    review_count: 223,
    categories: [
      {
        alias: "taiwanese",
        title: "Taiwanese",
      },
      {
        alias: "bubbletea",
        title: "Bubble Tea",
      },
      {
        alias: "noodles",
        title: "Noodles",
      },
    ],
    rating: 3.8,
    coordinates: {
      latitude: 32.91324997199857,
      longitude: -117.1489520419781,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "9690 Reagan Rd",
      address2: "Ste 104",
      address3: null,
      city: "San Diego",
      zip_code: "92126",
      country: "US",
      state: "CA",
      display_address: ["9690 Reagan Rd", "Ste 104", "San Diego, CA 92126"],
    },
    phone: "",
    display_phone: "",
    distance: 13649.86090645038,
  },
  {
    id: "NxvB55P2UCjeAcEPsJwyUw",
    alias: "flama-llama-san-diego",
    name: "Flama Llama",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/YBTWUzh51i7StVF6NX-EFg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/flama-llama-san-diego?adjust_creative=wieZL2d874d6yAqQIh_gnQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=wieZL2d874d6yAqQIh_gnQ",
    review_count: 1970,
    categories: [
      {
        alias: "latin",
        title: "Latin American",
      },
      {
        alias: "peruvian",
        title: "Peruvian",
      },
      {
        alias: "asianfusion",
        title: "Asian Fusion",
      },
    ],
    rating: 4.7,
    coordinates: {
      latitude: 32.821134,
      longitude: -117.154646,
    },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "4433 Convoy St",
      address2: null,
      address3: "",
      city: "San Diego",
      zip_code: "92111",
      country: "US",
      state: "CA",
      display_address: ["4433 Convoy St", "San Diego, CA 92111"],
    },
    phone: "+18584920402",
    display_phone: "(858) 492-0402",
    distance: 3395.7866090726147,
  },
  {
    id: "b9XtSjDs4zRisGVmZ9qBhw",
    alias: "yuk-dae-jang-san-diego",
    name: "Yuk Dae Jang",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/5pMq6q0WntoQHZmitJpOzg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/yuk-dae-jang-san-diego?adjust_creative=wieZL2d874d6yAqQIh_gnQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=wieZL2d874d6yAqQIh_gnQ",
    review_count: 172,
    categories: [
      {
        alias: "korean",
        title: "Korean",
      },
    ],
    rating: 4.6,
    coordinates: {
      latitude: 32.831895948715214,
      longitude: -117.16058658466224,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "7307 Clairemont Mesa Blvd",
      address2: "",
      address3: null,
      city: "San Diego",
      zip_code: "92111",
      country: "US",
      state: "CA",
      display_address: ["7307 Clairemont Mesa Blvd", "San Diego, CA 92111"],
    },
    phone: "+18587374002",
    display_phone: "(858) 737-4002",
    distance: 4635.315091780181,
  },
  {
    id: "AvkmeiPuyX6gaVjxRkAhWA",
    alias: "ten-seconds-yunnan-rice-noodle-san-diego",
    name: "Ten Seconds Yunnan Rice Noodle",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/-XBahUdU0MfvPcuDGu5W9Q/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/ten-seconds-yunnan-rice-noodle-san-diego?adjust_creative=wieZL2d874d6yAqQIh_gnQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=wieZL2d874d6yAqQIh_gnQ",
    review_count: 106,
    categories: [
      {
        alias: "noodles",
        title: "Noodles",
      },
    ],
    rating: 4.4,
    coordinates: {
      latitude: 32.825823,
      longitude: -117.152766,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "7905 Engineer Rd",
      address2: null,
      address3: "",
      city: "San Diego",
      zip_code: "92111",
      country: "US",
      state: "CA",
      display_address: ["7905 Engineer Rd", "San Diego, CA 92111"],
    },
    phone: "+18588981588",
    display_phone: "(858) 898-1588",
    distance: 3922.9152948642595,
  },
];
